# Generated by Django 2.2.7 on 2019-11-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='emial',
            new_name='email',
        ),
    ]
